# Generated by Django 4.1.3 on 2022-12-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_hasimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="hasImage",
            field=models.BooleanField(default=False),
        ),
    ]
