# Generated by Django 4.1.2 on 2022-11-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_imageattachment_remove_newsarticle_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='images',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageAttachment',
        ),
    ]
